// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/dashboard/_middleware.ts";
import * as $3 from "./routes/dashboard/index.tsx";
import * as $4 from "./routes/enroll-mfa.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/set-password.tsx";
import * as $7 from "./routes/sign-in.tsx";
import * as $8 from "./routes/verify-mfa.tsx";
import * as $$0 from "./islands/dashboard.tsx";
import * as $$1 from "./islands/mfa-enrollment.tsx";
import * as $$2 from "./islands/set-password-form.tsx";
import * as $$3 from "./islands/sign-in-form.tsx";
import * as $$4 from "./islands/url-parser.tsx";
import * as $$5 from "./islands/verify-mfa.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/dashboard/_middleware.ts": $2,
    "./routes/dashboard/index.tsx": $3,
    "./routes/enroll-mfa.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/set-password.tsx": $6,
    "./routes/sign-in.tsx": $7,
    "./routes/verify-mfa.tsx": $8,
  },
  islands: {
    "./islands/dashboard.tsx": $$0,
    "./islands/mfa-enrollment.tsx": $$1,
    "./islands/set-password-form.tsx": $$2,
    "./islands/sign-in-form.tsx": $$3,
    "./islands/url-parser.tsx": $$4,
    "./islands/verify-mfa.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
